import Head from "next/head";
import Image from "next/image";
// Styles
import styles from "../styles/Home.module.css";
// Components
import Banner from "../components/banner";
import Card from "../components/card";

import coffeeStoresData from "../data/coffee-stores.json";
// Types
import { coffeeStoreType } from "../data.types";

export async function getStaticProps(context: any) {
  return {
    props: { coffeeStores: coffeeStoresData },
  };
}

interface Props {
  coffeeStores: coffeeStoreType[];
}

const Home: React.FC<Props> = ({ coffeeStores }) => {
  const handleOnBannerBtnClick = () => {
    console.log("Hi banner button");
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText="View stores nearby"
          handleOnClick={handleOnBannerBtnClick}
        />
        <div className={styles.heroImage}>
          <Image
            src="/static/hero-image.png"
            width={700}
            height={400}
            alt="Hero"
          />
        </div>
        {coffeeStores.length > 0 ? (
          <>
            <h2 className={styles.heading2}>Toronto stores</h2>
            <div className={styles.cardLayout}>
              {coffeeStores.map((store) => (
                <Card
                  key={store.id}
                  name={store.name}
                  imgURL={store.imgUrl}
                  href={`/coffee-store/${store.id}`}
                  className={styles.card}
                />
              ))}
            </div>
          </>
        ) : (
          ""
        )}
      </main>
    </div>
  );
};

export default Home;
